### ISSUE TITLE
Staff Tag Edit Shows for Hidden Staff

### ISSUE THREAD

**Issue by FlyingSixtySix** [philomena-dev/philomena#1]
**Describe the bug**
When viewing the tag edit history for an image, the box saying, "Stop! This user is a staff member. Ask them before reverting their changes," will show regardless of whether or not they are listed on the site staff page.

**To Reproduce**
1. Click on 'History (n)' button on an image where a hidden staff member has edited tags
2. See box saying they are a staff member
3. See their user box missing from the site staff list

**Expected behavior**
The staff member's tag edit should appear normally and without the "Stop!" box if they are hidden from the site staff page.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 83.0.478.61 (Official build) (64-bit)

**Additional context**
N/A

**Comment by liamwhite** [comment]
b58bb87d7157566e5abca56c0627e26bf9d5b16b
