### ISSUE TITLE
It is impossible to get tag names by ID

### ISSUE THREAD

**Issue by GiorgioProductions** [philomena-dev/philomena#114]
I am unable to display the tags hidden by a filter because there is no way in the API to fetch a tag by its ID and a filter response only returns the tags IDs.
![imagen](https://user-images.githubusercontent.com/15032780/115935918-7e89b080-a494-11eb-9633-0eef5d51bfaa.png)
![imagen](https://user-images.githubusercontent.com/15032780/115935921-8184a100-a494-11eb-9376-39aa7633645c.png)

**Comment by liamwhite** [comment]
use `id:1 || id:2 || id:3 || ...`
for example [/api/v1/json/search/tags?q=id:1+||+id:3+||+id:4](https://derpibooru.org/api/v1/json/search/tags?q=id%3A1+||+id%3A3+||+id%3A4)

**Comment by GiorgioProductions** [comment]
Thank you so much! Could you mention this in the API docs?
