### ISSUE TITLE
Add option to create complex watch/spoiler/hide expression straight from tag list under an image

### ISSUE THREAD

**Issue by HushedFox** [philomena-dev/philomena#121]
**Is your feature request related to a problem? Please describe.**
Adding complex expressions is not so easily available as doing this for single tags. When I see image with a theme described with more than one tag (e.g. I want to see more of the character `astra` but only when they are `fluffy` and `solo` (`astra AND fluffy AND solo`) or I don't want to see those), I can't add such expression straight from the image I spotted with that theme. This 

**Describe the solution you'd like**
Add a button that would start the process of creating complex watch/spoiler/hide expressions from list of tags under an image:

![image](https://user-images.githubusercontent.com/17304608/120531017-6e8fb580-c3de-11eb-9909-b3a6a837206b.png)

Now there would be an option to select tags by clicking on them and they would automatically be added to an expression:

![image](https://user-images.githubusercontent.com/17304608/120537120-363fa580-c3e5-11eb-99eb-e7393b6a6265.png)

Maybe this could also provide abbility to add things different than AND, that is OR or NOT 

![image](https://user-images.githubusercontent.com/17304608/120532039-90d60300-c3df-11eb-8eb4-d705c9128044.png)

But "OR" will need brackets to work properly. So maybe just AND and NOT? It's easy to edit it later in the text box but maybe idk, for mobile users?

Anyway, after clicking on save the expression would be added as a new line to either complex watch or complex spoiler or complex hide.

**Comment by Meow** [comment]
Not really feasible to implement considering our planned updates to the tag editor and the tagbox. Could perhaps be a userscript, though.
