### ISSUE TITLE
Missing deleted filter on featured lookup

### ISSUE THREAD

**Issue by liamwhite** [philomena-dev/philomena#124]
https://github.com/philomena-dev/philomena/blob/70a81095be094346e20a619fe10da639d439e514/lib/philomena_web/controllers/activity_controller.ex#L72-L80

**Comment by SomewhatDamaged** [comment]
Probably need to add here too:

https://github.com/philomena-dev/philomena/blob/70a81095be094346e20a619fe10da639d439e514/lib/philomena_web/controllers/api/json/image/featured_controller.ex#L12-L19
