### ISSUE TITLE
Add anti-poopsocking settings (a.k.a. noprocrast mode)

### ISSUE THREAD

**Issue by PubliqPhirm** [philomena-dev/philomena#125]
### What it is?

A user-configurable set of settings that voluntarily lock you out after spending some set amount of time on the booru.

### Why?

Exactly why depends on each specific user who enables this feature.  A common case would be to stop refreshing the watched list all day and instead limit yourself to one end-of-day session.

### Potential downsides & caveats

* Could be another tool for mod abuse (though they already have temp bans available to handle/bother trouble users)
* Could erase comments typed and then submitted after the timer expired.  Comments like that should instead post successfully and display a page stating something like "Comment successfully posted.  However, you're now in no clop mode for the next `n` minutes."
* Users may want more complex settings than "a maximum of X minute sessions with a minimum of Y between visits".  For example, they want 20-minute sessions with at least 4 hours away for most of the week but then have a single 4-hour marathon pony party on Saturday evenings.

**Comment by Meow** [comment]
I don't think a feature like that is warranted in the core software. Could be a browser plugin, perhaps?
