### ISSUE TITLE
Help understanding where the admin settings are

### ISSUE THREAD

**Issue by MetallicAchu** [philomena-dev/philomena#127]
**Describe the bug**
Not sure it's a bug - sorry about that.
Where are the administrator settings? 
I've logged on successfully with the default information, tried to change my password and managed to do so, but I can't find any settings.

For example: where is the SMTP settings? Where can I set some behaviours for the gallery?

Thank you

**Comment by liamwhite** [comment]
Most such settings are configured through environment variables, not through the web UI (it doesn't make much sense to put them in the web UI). You can find a list of those [here](https://github.com/philomena-dev/philomena/blob/master/config/runtime.exs).
