### ISSUE TITLE
Searching for query that includes brackets and using wildcard * gives no results.

### ISSUE THREAD

**Issue by HushedFox** [philomena-dev/philomena#149]
**Describe the bug**
When trying to search for a query that has brackets and also using wildcard `*` in it gives no results. This problem is especially severe on Furbooru as there are lots of tags that have brackets in them.

**To Reproduce**
1. Go to image search: https://derpibooru.org/search
2. Type ` twilight sparkle (a*`
4. See that there are no results, but there is a tag [twilight sparkle (alicorn)](https://derpibooru.org/tags/twilight+sparkle+%2528alicorn%2529) that should be shown here

The same can be seen here, in tag search:
1. Go to tag serach: https://derpibooru.org/tags
2. Type ` twilight sparkle (a*`
4. See that there are no results, but there is a tag [twilight sparkle (alicorn)](https://derpibooru.org/tags/twilight+sparkle+%2528alicorn%2529) that should be shown here

**Expected behavior**
Wildcard should work and there should be results for matching tags.

**Screenshots**
On Derpibooru there is a tag called `twilight sparkle (alicorn)`
![image](https://user-images.githubusercontent.com/17304608/145711709-29b6a11c-e858-4a6c-9f27-74087a0d992a.png)
When I try to search for it there are no results, image search:
![image](https://user-images.githubusercontent.com/17304608/145711751-01472b96-457e-441c-b52a-fdef2d74fa84.png)
tag search:
![image](https://user-images.githubusercontent.com/17304608/145711743-d77d8e2d-00c5-469d-b458-321afee5fb84.png)

**Comment by liamwhite** [comment]
This is not no results, this is a parse error. To search for expressions with imbalanced parentheses, you must either escape or quote the term:
- `twilight sparkle \(a*`
- `"twilight sparkle (a*"`

**Comment by HushedFox** [comment]
But I think I remember it working fine in the past, but maybe I am mistaken.

But anyway, this is not a good behavior from the perspective of the user. There is no information provided about how to search with brackets so that results are properly displayed on the search page directly. In the very least if such error is encountered it should inform the user about how to search for intended thing, but the ideal solution would be to change user input of this kind into proper query. The site should assume that input `twilight sparkle (a*` is equal to the ones you provided and use this instead.

On Furbooru every character tag has brackets in its name, so it's kind of important for such things to be user friendly...
![image](https://user-images.githubusercontent.com/17304608/145716479-418d5d6a-da35-4e7b-b5d4-61cd4524c1ac.png)
