### ISSUE TITLE
Calculate total words written

### ISSUE THREAD

**Issue by PubliqPhirm** [philomena-dev/philomena#158]
**Is your feature request related to a problem? Please describe.**
[Needed to implement a proposed Derpibooru badge based on total word count](https://derpibooru.org/forums/meta/topics/derpiboorus-badges?post_id=5216507#post_5216507), if the badge is accepted.

**Describe the solution you'd like**
Implement a way to total up the word count for each user.  Could also perform interesting calculations such as the total word counts of a forum thread, image's comment section, or the entire corpus of user-submitted text on the whole site.  Word counting could be accomplished with the same function as gets used to implement #157 

_Open design questions_
1. Who gets to view the number?  Is it for staff only, the user+staff, logged-in users, or the entire internet?  In any of these cases, it would presumably be listed somewhere on the user's profile page.
2. Do staff have some kind of search box to find users (`account_age.gte:1 month ago, !banned`)?  If so, is it worthwhile to add a search field like `total_words.lt:123456`?

**Describe alternatives you've considered**
Not having such vanity metrics?

**Additional context**
These metrics do **not** need to be live-updated.  If it's somehow less load on the servers to run a nightly or weekly recalculation (or 
not implementing a grand total word count for the whole site), that's just fine.

**Comment by Meow** [comment]
A badge based on total words written would be something to consider if we were a fiction-hosting site, however I don't think it's something we want to have. It'd also encourage people to write text walls, which would also encourage writing around the bush or writing useless things you'd not otherwise write.

**Comment by Meow** [comment]
This feature is rather niche and as proposed will take up additional database space, search index space, and compute resources. Instead, in the redesign, we'll provide words written counter in the text editor.
