### ISSUE TITLE
Demo site?

### ISSUE THREAD

**Issue by hawkoon** [philomena-dev/philomena#16]
Is there a demo site available for this software?

**Comment by liamwhite** [comment]
most prominently used by https://derpibooru.org and https://furbooru.org

do you need something further?

**Comment by hawkoon** [comment]
Imageboards don't require an account. This is more a 'booru' software than an imageboard.

**Comment by liamwhite** [comment]
That is an almost-pointless semantic distinction, given that the terminology "imageboard" is used to refer to both *chans and boorus. Yes, this is a booru project.

No account is required to post to either site linked above.
