### ISSUE TITLE
Philomenia app (code 127)  and web (code 1) exits with no real explenation

### ISSUE THREAD

**Issue by ShiftTGC** [philomena-dev/philomena#165]
**Describe the bug**
For whatever reason, Docker compiles just fine, but unless I am _supposed_ to do setup with config files which "getting started" has not mentioned, it ends up with exiting out of app_1 (code 127) followed by web_1 (code 1) not long after.
I'm by no means a docker expert, but I can't see any reason as to why it just stops.

**To Reproduce**
1. Get WSL 2 and Docker Desktop configured (with pc restart)
2. Open cmd in administrator mode. 
3. cd to where you want to setup Philomena (D:\shiftbooru)
4. git clone https://github.com/philomena-dev/philomena.git
5. cd philomena
6. docker-compose build (No errors)
7. docker-compose up (wait untill attaching to the containers)
8. !profit

**Expected behavior**
A localhost site of Philomena/derpibooru clone to run.
(Have had semi-success in the past with 2 out of 3 VMs. Was buggy and broken tho.)

**Screenshots**
![hHxHxWYHxO](https://user-images.githubusercontent.com/50029001/161055299-3a0a1cf8-9885-4afb-bdca-b672f845089b.png)
![2oicYeEEs0](https://user-images.githubusercontent.com/50029001/161050758-072da2f3-d596-410f-a8e8-e40a05ae1c82.png)
![9kRBbk80fC](https://user-images.githubusercontent.com/50029001/161050762-82b72209-cc6a-4888-98d7-13acb5b56c22.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home - 21H2
 - Docker Desktop version: 4.6.1 (76265) 
 - WSL 2 enabled

**Additional context**
 - Port 80 is not in use by any other service.

Entire cmd log, from install to where it just stops. (tried the troubleshooting steps)
[philomania install from start to error - app 1 exited code 127 - host not found upstream - web 1 exited with code 1 - ShiftTGC.txt](https://github.com/philomena-dev/philomena/files/8389123/philomania.install.from.start.to.error.-.app.1.exited.code.127.-.host.not.found.upstream.-.web.1.exited.with.code.1.-.ShiftTGC.txt)

The most notable things I will assume would be:
philomena-app-1 exited with code 127

philomena-web-1            | 2022/03/31 11:44:38 [emerg] 1#1: host not found in upstream "app:4000" in /etc/nginx/conf.d/default.conf:2
philomena-web-1            | nginx: [emerg] host not found in upstream "app:4000" in /etc/nginx/conf.d/default.conf:2 

philomena-web-1 exited with code 1

**Comment by liamwhite** [comment]
"Host not found in upstream" means that the docker network isn't being properly configured. There are 5 networked services (app, postgres, elasticsearch, redis, and web) that access each other via internal DNS in the development configuration. You might want to check whether using a different network type to join the services would fix the problem.

**Comment by liamwhite** [comment]
Need more info.
