### ISSUE TITLE
Searching by "initial post date" has inaccurately sorted oldest results

### ISSUE THREAD

**Issue by UngoliantGloomweaver** [philomena-dev/philomena#177]
**Describe the bug**
The last results for at least one specific search query with default sorting (initial post date) are not sorted by oldest to newest starting from the end. On the specific query I noticed the issue with the jumbled results are all from the same day, but the timestamp ordering is seemingly random (at least with front facing information) and doesn't follow the "upload" date sorting.

**To Reproduce**
1. search "webm"
2. hit "last" on page listing
3. wonder why the oldest uploads aren't the last on the list

**Expected behavior**
That sorting by "initial post date" would list by upload date, not whatever column is used that differs from that information. Or just sort by Id by default, since the incremental nature of ids would result in the exact same result, IF it wasn't borked.

**Desktop (please complete the following information):**
 - Windows
 - Chrome (I know, I know, booo chrome, byte me)
 - Version 111.0.5563.147

**Additional context**
Preproduced by other users as well

**Comment by liamwhite** [comment]
There isn't any bug here -- the sorting is fully correct based on the underlying data, the issue is that maybe first_seen_at isn't an expected way to order images by default.
