### ISSUE TITLE
I'm a newbie, how do I disable email confirmation or make it work?

### ISSUE THREAD

**Issue by BrenoMartinsDeOliveiraVasconcelos** [philomena-dev/philomena#198]
I can't confirm email while using my own instance

**Comment by liamwhite** [comment]
If you are running in prod, set up a SMTP relay <https://github.com/philomena-dev/philomena/blob/master/config/runtime.exs#L113-L123>
If you are running a dev instance, the token will get logged to the console when the account is created.
