### ISSUE TITLE
FontAwesome 6 Support (Free & Pro)

### ISSUE THREAD

**Issue by chaskayote** [philomena-dev/philomena#227]
**Is your feature request related to a problem? Please describe.**
A problem of laziness. Hunting down SVGs for different uses, such as badges, isn't the most fun and FontAwesome has so many options for free available from their API.

**Describe the solution you'd like**
Ability to select FontAwesome 6 icons for badges, forum topics, and default avatars.

**Describe alternatives you've considered**
Download FontAwesome item individual as svg and uploading manually bleh.

**Additional context**
Merp

**Comment by liamwhite** [comment]
At first I thought this was a request to upgrade to FA6, so I checked package.json and it was already at that version. Might have been worth a title clarification...

The icons for badges, topics and default avatars are intended to give character and be specific to the domain you are running - I'm not convinced there's a good reason to have any of these premade in upstream repositories, and there are of course plenty of [examples](https://derpibooru.org/forums/meta/topics/badges-and-stuff).
