### ISSUE TITLE
Pop-up Overlay asking if 18+

### ISSUE THREAD

**Issue by kemopup** [philomena-dev/philomena#251]
**Is your feature request related to a problem? Please describe.**
By US law, and many other countries, an adult website must prompt that you are at least over 18 before any content is shown. Right now SFW shows by default and you have to go out of your way to Filters to enable Everything. While doing this, you are never prompted to confirm you're at least 18.

**Describe the solution you'd like**
When you arrive on any page on a Philomena website, a prompt comes up asking if you're 18+. If No is selected, only safe and suggestive pieces load. If Yes is selected, site loads as normal.

**Describe alternatives you've considered**
Due to US law, there is no available alternative that I can think of besides coding something separate for the site you've forked.

**Additional context**
There should probably be an environmental variable where you can set required age.

**Comment by Meow** [comment]
We already sufficiently warn users about this by stating `...by changing away from the default filters, you accept you are legally permitted to view this content in your jurisdiction` on the filters page. I think this sufficiently (in legal sense) substitutes a popup warning that you're proposing.
