### ISSUE TITLE
Aliased tags don't get changed in filters

### ISSUE THREAD

**Issue by parasprite** [philomena-dev/philomena#27]
If you add an aliased tag to a filter, it doesn't get changed to the corresponding aliased tag, and it probably should automatically for usability purposes. I also don't know off-hand if BoR handled it this way or not.

1. Alias pegasi to pegasus
2. Add pegasi to filter
3. Filter shows pegasi (0)
4. Searching pegasus shows all pegasi

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/c7cd7f3af3990d41d461511f0dddb59b1b1832fe
