### ISSUE TITLE
Rename sort by upload date to sort by ID

### ISSUE THREAD

**Issue by basisbit** [philomena-dev/philomena#32]
**Describe the bug**
Sort by upload date sorts by ID, not by upload date.

**To Reproduce**
1. Increase the next-id counter in the DB to 10
2. Upload an image
3. Decrease the next-id counter in the DB to 1
4. Upload up to 9 images

The first uploaded image will be shown as most recent / newest image.

**Expected behavior**
The main page, the image processing queue as well as when searching using the sort order "Sort by upload date" should all show the images in order of upload date/time.

Many imageboard users probably want to see "new" art on the main page, no matter the source and numbers-region.

**Screenshots**

**Additional context**
Some of the philomena boorus use different image ID number-regions to make it easier to differentiate image origin and also to make it easier to merge imageboards without breaking links from outside of the imageboard. For Example Derpibooru uses 1 (to 3.999.999), Manebooru uses 4.000.000 (to 5.999.999), and ponerpics uses 6.000.000+ as new image IDs.
If we continue the route to federated boorus, at least for some time there probably will be boorus importing images from other boorus (those which are alife and those which are closing their imageboard).

**Comment by liamwhite** [comment]
This is intentional. Using IDs outside the scope of incrementing order by upload date is not supported.

**Comment by basisbit** [comment]
in that case the search option should at least be renamed, because it does not actually sort by upload date, but instead by ID. Yes, in typical setups this will have the same result, but technically it is still a bug.

**Comment by liamwhite** [comment]
That's fine, I will do that.
