### ISSUE TITLE
Self Hosted Application for local/small environment

### ISSUE THREAD

**Issue by deckyfx** [philomena-dev/philomena#346]
**Is your feature request related to a problem? Please describe.**
The repo for now seems asking it to be hosted on AWS cloud, 

**Describe the solution you'd like**
Is there any way to host this booru? for example, using casaos?

**Describe alternatives you've considered**
Also is there any prebuilt image?

**Comment by Meow** [comment]
Local dev environment doesn't require any cloud. Personally speaking, in production, we host the main machine with all the docker containers at OVH, and store images in Cloudflare R2.
