### ISSUE TITLE
Feature request: Mark comment as "bait"

### ISSUE THREAD

**Issue by Xaekai** [philomena-dev/philomena#4]
There should be a middle ground between outright deleting comments and just letting something inappropriate slide by.

Something where the entire post/comment is spoilered, and requires affirmative consent by a click for the viewer to see. Additionally, quoting and replying button functionality should be disable for such posts. If you are gonna reply to bait, you need to work for it.

**Comment by liamwhite** [comment]
The problem with bait posting runs deeper than just discouraging users from interacting with bait posts. Acknowledging the post is bait to begin with through visible moderation tools still fulfills the purpose of the poster (to get a rise out of someone). The only solution I can think of that really completely undermines the ability of people to post bait is something like [xkcd 810](https://xkcd.com/810/), but that might be so invasive it discourages anyone from using the site at all.

**Comment by Xaekai** [comment]
There are also many times where someone may not realize just how far they've gone off track, but their comment retains enough value it should not be outright deleted. A tool need not be 100% efficacious to warrant existence. This is one area where a binary set of states doesn't accurately represent reality. Especially since the service offered by this software has richtext comments/posts where one could spend a significant amount of time writing something, to the point where a careless mod on a bad day choosing to just delete it because there are no other easy options comes across as gravely insulting to the user.

**Comment by LucidUnrest** [comment]
I agree, the ability to partial hide comments as a mod tool could be useful when such comments are either off topic, semi-inappropriate, or just down right unhelpful or rude. 

Ive made a quick example of what that could look like. 

![example 1](https://user-images.githubusercontent.com/55334247/89864618-193d9b80-db61-11ea-8e90-b8f379908231.png)

**Comment by Meow** [comment]
I doubt publicly pointing out content as bait is useful in any manner. And we already have a spoilering syntax in Markdown, which if combined with `CW: whatever` text prepended to it, substitutes this proposal for showing unfilterable content. Implementation not necessitated.
