### ISSUE TITLE
Quick tags table sorts alphabetically instead of the order written in the config

### ISSUE THREAD

**Issue by parasprite** [philomena-dev/philomena#51]
![Screenshot 2020-10-19 104235](https://user-images.githubusercontent.com/12550523/96473936-d8fd3800-11f7-11eb-9ac5-5a5527627648.png)
For instance, Mane cast here should be first, Fillies and Colts last, and the list itself should be sorted like this:
```
     "Mane Cast": {
      "m6": "mane six",
      "pt": "princess twilight",
      "ts": "twilight sparkle",
      "rd": "rainbow dash",
      "ry": "rarity",
      "aj": "applejack",
      "fs": "fluttershy",
      "pp": "pinkie pie",
      "sp": "spike"
    },
```

**Comment by liamwhite** [comment]
It doesn't sort alphabetically necessarily, it sorts according to the internal ordering of the [HAMT](https://en.wikipedia.org/wiki/Hash_array_mapped_trie). To fix this, change the JSON object to an array.

**Comment by parasprite** [comment]
I'll see what I can do.
