### ISSUE TITLE
Meta tags on /tags page are case sensitive

### ISSUE THREAD

**Issue by parasprite** [philomena-dev/philomena#57]
Search `name:cute` and `Name:cute`. The latter won't return any results.

It's super minor but a bit unexpected. Comes up sometimes since mobile tends to capitalize things for you by default.

**Comment by liamwhite** [comment]
Would it be okay to just disable autocapitalize on search inputs?

**Comment by parasprite** [comment]
Not a full solution but it would probably help out from being noticed as
much.

Is there a reason you can't downcase the input?

**Comment by liamwhite** [comment]
The parser supports no-downcase fields, which (like the name implies) do not force the input to be lowercase. This means that when parsing, the code seeing a nonexistent field name will treat it as a tag instead.

**Comment by liamwhite** [comment]
This case sensitivity is consistent on all search inputs AFAIK. They also have autocapitalize=none set, so I don't really see the point in trying to shoehorn in case insensitivity into the parser.
