### ISSUE TITLE
Feature Request: Auxiliary sources list.

### ISSUE THREAD

**Issue by Xaekai** [philomena-dev/philomena#6]
Generally creators have a preferred canonical outlet for their works, however they also often exist as multiple entities across a range of services. An artist may release works across the whole galaxy of hosts from the old guards like DeviantArt and Tumblr, the ubiquitous commons like Twitter, Facebook, FurAffinity, InkBunny, Pixiv, Behance, Instagram and ArtStation, and newcomers like Toyhouse and Pillowfort, not to mention a selfhosted personal site. So since the same work could very well have have multiple official sources, it would be nice to have a surfaced method of retaining that metadata.

**Comment by Meow** [comment]
Checking in on this issue: does our recently introduced multiple sources functionality suffice for this purpose?
