### ISSUE TITLE
Ability to change title and slug of the forum topic separately

### ISSUE THREAD

**Issue by VcSaJen** [philomena-dev/philomena#7]
**Is your feature request related to a problem? Please describe.**
When the topic is renamed, URL is changed too, breaking all links.

**Describe the solution you'd like**
Ability to change slug of the topic, and title of the topic separately in mod tools. Then if you change only title, URL would stay the same (and reflect old title), while visible title would change.

**Describe alternatives you've considered**
You can also prefix url by post id, and use that, but that would initially break all existing links, so not a good solution.

**Additional context**
This came up quite many times recently, would be better if that was addressed.

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/014cb025fd587b15621dd357946823a85618e8be
