### ISSUE TITLE
Bypass rate limiting for non-staff

### ISSUE THREAD

**Issue by joeyponi** [philomena-dev/philomena#76]
**Is your feature request related to a problem? Please describe.**
Similar to the option to grant non-staff users access to the batch tagging system, could there be a flag added to allow trusted non-staff users the ability to bypass site rate limits on commenting, messaging, etc. Currently anyone flagged as site staff bypass these rate limits automatically, but there can be valid use cases where a non-staff user may need to post a copy/pasted message multiple times in rapid succession (this is mostly collab-related stuff since there's a lot of repetition there)

**Describe the solution you'd like**
A option under "General User Flags" to allow an admin or mod with appropriate roles to flag a user as being able to bypass the rate limit.

**Describe alternatives you've considered**
I tried being staff, that didn't work out too well.

**Additional context**
![image](https://user-images.githubusercontent.com/12476941/100771322-eba48880-33c3-11eb-8eab-e80aabc7722b.png)

**Comment by Meow** [comment]
Resolved via ae3411b7a26fb712a86ec1efbace353a66c395b3
