### ISSUE TITLE
Sort favorites by faved date

### ISSUE THREAD

**Issue by BytewaveMLP** [philomena-dev/philomena#79]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When searching for `my:faved` or `faved_by:USER` (or `faved_by_id:USER_ID`), it would be nice to be able to sort the results by the date the images were favorited by the user using the `image_faves.created_at` field. I assume this would need to be implemented as a sort format for all queries, which would place favorited images at the top of the list (for `sd=desc`), and non-favorited images at the end.

**Describe alternatives you've considered**
- An account setting that controls the sorting of favorites (more difficult since faves lists are just search queries)

**Additional context**
N/A

**Comment by liamwhite** [comment]
Currently there is no way to efficiently do this in elasticsearch. The data are being tracked in the hopes that one day it will be possible, but for now it simply can't be done.
