### ISSUE TITLE
View counter on images feature request

### ISSUE THREAD

**Issue by LucidUnrest** [philomena-dev/philomena#93]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A view counter listed somewhere in the user interaction bar, tracked by unique IP or user account

**Describe alternatives you've considered**
N/A

**Additional context**
Ive included a rough mockup of the idea 
![9ExuvRy 1](https://user-images.githubusercontent.com/55334247/104872871-4bbba380-590c-11eb-91a2-4b36bf26ba5c.png)

**Comment by liamwhite** [comment]
This was implemented in a fork in https://github.com/ZizzyDizzyMC/philomena/commit/4b351af5bbcd2e78e0e447852f207f802d41bdcc . I don't really feel interested in implementing it here:
- unlike like e.g. vote/fave times or advert impressions, views are public facing and so present themselves as a target for manipulation
- views are somewhat ill-defined, on hidpi devices my "viewing" of an image from the index page is often enough
- "view count" is not as useful as a metric as "semi-distinct views", which requires extra storage and a dedicated background task for rolling it over and aggregating distinct views periodically
- postgres famously has a bit of a hard time with row churn for updates. (yes you can mitigate this with HOT and normalization and increasing vacuum parameters and aggregating writes, but still, there are penalties)
- no data actually exists for most sites running this software and would have to start from zero or be estimated

For these reasons, closing as won't fix.
