### ISSUE TITLE
Reverse image search fails to match identical RGBA PNG images with any sensitivity

### ISSUE THREAD

**Issue by VcSaJen** [philomena-dev/philomena#95]
**Describe the bug**
When trying to reverse-search transparent PNG image, no matter how much you adjust "Match distance" value, site will fail to find source image.

**To Reproduce**
1. Go to https://derpibooru.org/images/442297
2. Scale down your browser window
3. Right-click on image and then choose "Save X as..." option, and save small.png/medium.png/large.png file
4. Go to https://derpibooru.org/search/reverse , click on "Browse..." button, choose image you saved in step 3. Then enter any number for "Match distance", and click on "Reverse search".
5. Results will never find source image

**Expected behavior**
Site should find source image

**Likely reason**
Most likely this happens because when site scale-down images for thumbs, it doesn't preserve color value of fully-transparent pixels, making them all black. Then when user tries to search full image by thumb image, reverse search executes image-intensities, and it calculates only RBG values, ignoring Alpha. When source image have non-black color for fully-transparent pixels, reverse search will fail to find source image.
Example:
[![original](https://dl.dropboxusercontent.com/s/z4dsi3ct0dtq7zg/442297-rgb-64px.png?dl=0)](https://dl.dropboxusercontent.com/s/ehg1mr3ldd2bp40/442297-rgb.png?dl=0) [![scaled](https://dl.dropboxusercontent.com/s/jrl4o06o7nole2d/large-rgb-64px.png?dl=0)](https://dl.dropboxusercontent.com/s/vytaqze1d08mfcv/large-rgb.png?dl=0)
I extracted RGB values from PNG, left is original (442297.png), right is scaled by site (large.png).
There are two ways to fix this. In image_intensities, when calculating:
1. assume RBG value to be (0;0;0) when Alpha is 0. Or,
2. multiply RBG value to Alpha value

**Screenshots**
See above

**Desktop:**
 - OS: any
 - Browser any
 - Version any

**Smartphone:**
 - Device: any
 - OS: any
 - Browser any
 - Version any

**Additional context**
No additional context

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/cli_intensities/commit/656c5af4fec3cba4d5ba8d6689f7620a85860c59

Transparent values are now composited on black; existing sites will need to recalculate intensities to take advantage of this fix.
