### ISSUE TITLE
view_url does not include ID on image:create

### ISSUE THREAD

**Issue by FlyingSixtySix** [philomena-dev/philomena#97]
**Describe the bug**
When receiving the `image:create` event over the firehose websocket, `image.view_url` does not include the image ID leading the filename.  For example:
```json
view_url: 'https://derpicdn.net/img/view/2021/2/10/__safe_artist-colon-scarlet-dash-spectrum_oc_oc+only_alicorn_pony_alicorn+oc_horn_solo_wings.png'
```

**To Reproduce**
1. Listen to firehose websocket at `/socket/websocket?vsn=2.0.0&key={{ key }}`
2. Receive `image:create` event
3. See `image.view_url` property

**Expected behavior**
The `image.view_url` property should include the ID leading the filename.  Using the example above:
```json
view_url: 'https://derpicdn.net/img/view/2021/2/10/2548251__safe_artist-colon-scarlet-dash-spectrum_oc_oc+only_alicorn_pony_alicorn+oc_horn_solo_wings.png'
```

**Comment by liamwhite** [comment]
This is a data issue which arises because the image's ID is stored in its `file_name_cache`.

The most workable fix at this point is to eliminate the use of `file_name_cache` as it should generally should no longer be necessary for performance.
